export const locationAreas = [
  { slug: "oldham", label: "Oldham", href: "/mobile-tyre-fitting-oldham" },
  { slug: "chadderton", label: "Chadderton", href: "/mobile-tyre-fitting-chadderton" },
  { slug: "royton", label: "Royton", href: "/mobile-tyre-fitting-royton" },
  { slug: "shaw", label: "Shaw", href: "/mobile-tyre-fitting-shaw" },
  { slug: "failsworth", label: "Failsworth", href: "/mobile-tyre-fitting-failsworth" },
  { slug: "saddleworth", label: "Saddleworth", href: "/mobile-tyre-fitting-saddleworth" },
  { slug: "manchester", label: "Manchester", href: "/mobile-tyre-fitting-manchester" },
  {
    slug: "manchester-city-centre",
    label: "Manchester City Centre",
    href: "/mobile-tyre-fitting-manchester-city-centre",
  },
  { slug: "ancoats", label: "Ancoats", href: "/mobile-tyre-fitting-ancoats" },
  { slug: "uppermill", label: "Uppermill", href: "/mobile-tyre-fitting-uppermill" },
  { slug: "cheetham-hill", label: "Cheetham Hill", href: "/mobile-tyre-fitting-cheetham-hill" },
  { slug: "blackley", label: "Blackley", href: "/mobile-tyre-fitting-blackley" },
  { slug: "chorlton", label: "Chorlton", href: "/mobile-tyre-fitting-chorlton" },
  { slug: "didsbury", label: "Didsbury", href: "/mobile-tyre-fitting-didsbury" },
  { slug: "gorton", label: "Gorton", href: "/mobile-tyre-fitting-gorton" },
  { slug: "longsight", label: "Longsight", href: "/mobile-tyre-fitting-longsight" },
  { slug: "moston", label: "Moston", href: "/mobile-tyre-fitting-moston" },
  { slug: "newton-heath", label: "Newton Heath", href: "/mobile-tyre-fitting-newton-heath" },
  { slug: "rochdale", label: "Rochdale", href: "/mobile-tyre-fitting-rochdale" },
] as const;
